routes:
  # =========================
  # Health Check Microservice
  # =========================

  - regex: '^/health(/*[a-zA-Z0-9]*)?'
    model: kotlinserverless.main.daos.Healthcheck
    controller: kotlinserverless.main.controllers.HealthcheckController
    
  # =========================
  # User Microservice
  # =========================
  
  - regex: '^/user(/*[a-zA-Z0-9]*)?'
    model: kotlinserverless.main.daos.User
    controller: main.controllers.UserController
