routes:
  # =========================
  # Health Check Microservice
  # =========================

  - regex: '^/health(/*[a-zA-Z0-9]*)?'
    model: kotlinserverless.framework.healthchecks.models.Healthcheck
    
  # =========================
  # User Microservice
  # =========================
  
  - regex: '^/user(/*[a-zA-Z0-9]*)?'
    model: kotlinserverless.main.users.models.User
